USE bateriacamiondb;

--------------------------------------------------------
-- Insercion de datos en procedimientos alamcenados --
--------------------------------------------------------

-- ROLES --
DELIMITER //
CREATE PROCEDURE AGREGAR_ROLES
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
	INSERT  INTO ROLES(EST_ROL, NOM_ROL)
    VALUES(EST, NOM);
END //

-- USUARIOS --
DELIMITER // 
CREATE PROCEDURE AGREGAR_USUARIO
(IN EST BOOLEAN, IN  NOMU VARCHAR(30), IN PASS VARCHAR(30), IN ROL INT)
BEGIN
	INSERT INTO USUARIOS(EST_USU, USER_USU, PASS_USU, ROL_ID)
    VALUES(EST, NOMU, PASS, ROL);
END //

-- EMPRESAS --
DELIMITER //
CREATE PROCEDURE AGREGAR_EMPRESAS
(IN EST BOOLEAN, IN NOM VARCHAR(30))
BEGIN
	INSERT INTO EMPRESAS(EST_EMP, NOM_EMP)
    VALUES(EST, NOM);
END //

-- TRABAJADORES --
DELIMITER //
CREATE PROCEDURE AGREGAR_TRABAJADORES
(IN NOM VARCHAR(30), IN APE VARCHAR(30), IN DNI VARCHAR(30), IN EST BOOLEAN ,IN USUARIO INT, IN EMPRESA INT)
BEGIN
	INSERT INTO TRABAJADORES(NOM_TRA, APE_TRA, DNI_TRA, EST_TRA, USUARIO_ID, EMPRESA_ID)
    VALUES(NOM, APE, DNI,EST, USUARIO, EMPRESA);
END //

-- CAMIONES --
DELIMITER //
CREATE PROCEDURE AGREGAR_CAMIONES
(IN PLACA VARCHAR(30), IN EMPRESA INT, IN TRABAJADOR INT, IN EST BOOLEAN)
BEGIN
	INSERT INTO CAMIONES(PLACA_CAM, EMP_ID, TRA_ID, EST_CAM)
    VALUES(PLACA, EMPRESA, TRABAJADOR, EST);
END //

-- BATERIAS --
DELIMITER //
CREATE PROCEDURE AGREGAR_BATERIAS
(IN NOMBRE VARCHAR(30), IN CAMION INT, IN EST BOOLEAN)
BEGIN
	INSERT INTO BATERIAS(NOM_BAT, CAM_ID, EST_BAT)
    VALUES(NOMBRE, CAMION, EST);
END //

-- DETALLE DE CAMIONES --
DELIMITER //
CREATE PROCEDURE AGREGAR_DETALLE_CAMIONES
(IN BATERIA INT, IN DIAD DATE, IN HORAD TIME, IN VOLTAJED DOUBLE, IN BATERIAD INT, IN TEMPERATURAD DOUBLE, IN EST BOOLEAN)
BEGIN
	INSERT INTO DETALLE_CAMIONES(BAT_ID, DIA, HORA, VOLTAJE, CARGA, TEMPERATURA, EST_DC)
    VALUES(BATERIA, DIAD, HORAD, VOLTAJED, BATERIAD, TEMPERATURAD, EST);
END //


--------------------------------------------------------
-- Insercion de datos en procedimientos alamcenados --
--------------------------------------------------------

-- ROLES --
CALL AGREGAR_ROLES(1,'ADMINISTRADOR');
CALL AGREGAR_ROLES(1,'CONDUCTOR');

-- USUARIOS --
CALL AGREGAR_USUARIO(1,'ADMIN','2121',1);
CALL AGREGAR_USUARIO(1,'RAULY2','E12FD',2);
CALL AGREGAR_USUARIO(1,'MAUIRO','2015DOS',2);

-- EMPRESAS --
CALL AGREGAR_EMPRESAS(1,'SurfaceItn');
CALL AGREGAR_EMPRESAS(1,'IMPORTPERIO');

-- TRABAJADORES --
CALL AGREGAR_TRABAJADORES('JUAN', 'TORRES', '78547689', 1, 1, 1);
CALL AGREGAR_TRABAJADORES('MARCO', 'ANTONIO', '41218722', 1, 2, 1);
CALL AGREGAR_TRABAJADORES('FRANK', 'MILLER', '78547688', 1, 3, 2);

-- CAMIONES --
CALL AGREGAR_CAMIONES('ABC-001', 1, 1, 1);
CALL AGREGAR_CAMIONES('ABC-002', 1, 2, 1);
CALL AGREGAR_CAMIONES('ABC-003', 2, 3, 1);
CALL AGREGAR_CAMIONES('ABC-007', 2, 3, 1);

-- BATERIAS --
CALL AGREGAR_BATERIAS('AZUS2201',1,1);
CALL AGREGAR_BATERIAS('AZUS2202',1,1);
CALL AGREGAR_BATERIAS('AZUS2203',1,1);
CALL AGREGAR_BATERIAS('AZUS2204',1,1);

-- DETALLE CAMIONES --
CALL AGREGAR_DETALLE_CAMIONES(1, '2023-05-25', '12:30:00', 12.5, 80, 25.5, 1);
CALL AGREGAR_DETALLE_CAMIONES(1, '2023-05-25', '13:30:00', 12.5, 70, 40.5, 1);
CALL AGREGAR_DETALLE_CAMIONES(1, '2023-05-25', '14:30:00', 12.5, 60, 20.3, 1);
CALL AGREGAR_DETALLE_CAMIONES(2, '2023-05-25', '12:30:00', 12.5, 90, 25.5, 1);
CALL AGREGAR_DETALLE_CAMIONES(2, '2023-05-25', '13:30:00', 10.5, 75, 30.2, 1);
CALL AGREGAR_DETALLE_CAMIONES(2, '2023-05-25', '14:30:00', 12.5, 60, 20.3, 1);
CALL AGREGAR_DETALLE_CAMIONES(3, '2023-05-25', '12:30:00', 10.5, 95, 25.5, 1);
CALL AGREGAR_DETALLE_CAMIONES(3, '2023-05-25', '13:30:00', 11.5, 81, 15.5, 1);
CALL AGREGAR_DETALLE_CAMIONES(3, '2023-05-25', '14:30:00', 10.5, 54, 20.3, 1);



SELECT * FROM ROLES;
SELECT * FROM USUARIOS;
SELECT * FROM EMPRESAS;
SELECT * FROM TRABAJADORES;
SELECT * FROM CAMIONES;
SELECT * FROM BATERIAS;
SELECT * FROM DETALLE_CAMIONES;

SELECT B.NOM_BAT, C.PLACA_CAM, E.NOM_EMP, T.NOM_TRA, T.APE_TRA
FROM BATERIAS B 
INNER JOIN CAMIONES C ON B.CAM_ID = C.ID_CAM
INNER JOIN EMPRESAS E ON C.EMP_ID = E.ID_EMP
INNER JOIN TRABAJADORES T ON C.TRA_ID = T.ID_TRA;



SELECT B.NOM_BAT, C.PLACA_CAM, D.DIA, D.HORA, D.VOLTAJE, D.CARGA, D.TEMPERATURA
FROM DETALLE_CAMIONES D
INNER JOIN BATERIAS B ON B.ID_BAT = D.BAT_ID
INNER JOIN CAMIONES C ON C.ID_CAM = B.CAM_ID
WHERE B.CAM_ID= 1;

SELECT * FROM DETACAMION;

DELIMITER //
CREATE PROCEDURE DETALLESVALORES
(IN CAMION INT)
BEGIN
	SELECT B.NOM_BAT, C.PLACA_CAM, D.DIA, D.HORA, D.VOLTAJE, D.CARGA, D.TEMPERATURA
	FROM DETALLE_CAMIONES D
	INNER JOIN BATERIAS B ON B.ID_BAT = D.BAT_ID
	INNER JOIN CAMIONES C ON C.ID_CAM = B.CAM_ID
	WHERE B.CAM_ID= 1;
END //

CALL DETALLESVALORES(3); 